<?xml version="1.0" encoding="utf-8"?><Database Name="TicTacToeDB" Class="TTTDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\TicTacToeDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TicTacToeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="IsAdvisor" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AdviseTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Player_Player" Member="Players" ThisKey="Id" OtherKey="AdviseTo" Type="Player" />
      <Association Name="Player_PlayerChampionship" Member="PlayerChampionships" ThisKey="Id" OtherKey="PlayerId" Type="PlayerChampionship" />
      <Association Name="Player_Game" Member="Games" ThisKey="Id" OtherKey="Player1" Type="Game" />
      <Association Name="Player_Game1" Member="Games1" ThisKey="Id" OtherKey="Player2" Type="Game" />
      <Association Name="Player_Game2" Member="Games2" ThisKey="Id" OtherKey="Winner" Type="Game" />
      <Association Name="Player_Player" Member="Player1" ThisKey="AdviseTo" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Championships" Member="Championships">
    <Type Name="Championship">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Association Name="Championship_PlayerChampionship" Member="PlayerChampionships" ThisKey="Id" OtherKey="ChampionshipId" Type="PlayerChampionship" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerChampionships" Member="PlayerChampionships">
    <Type Name="PlayerChampionship">
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChampionshipId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Championship_PlayerChampionship" Member="Championship" ThisKey="ChampionshipId" OtherKey="Id" Type="Championship" IsForeignKey="true" />
      <Association Name="Player_PlayerChampionship" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Player1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Winner" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Moves" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_Game" Member="Player" ThisKey="Player1" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Game1" Member="Player3" ThisKey="Player2" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Game2" Member="Player4" ThisKey="Winner" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
</Database>